### PR TITLE
Update 1.16 branch with 1.18 changes

### PR DESCRIPTION
**Pull request by FoxMcloud5655**
Updated the 1.16 version of XercaMusicMod to what's currently on 1.18.

Currently untested:
 * Midi device input
 * Metronome
 * Music Box
 * Hearing music on other clients

### CODE REVIEW

**Comment by ercanserteli** [comment]
I did a little testing and Midi device input and Hearing music on other clients seem to work fine. But the music box and metronome seem to not work at all. If you can fix those, I can do a more comprehensive test. 

If there are some problems you can't fix, I can do it too, but it will have to wait until I can find the time to dive into the code.

**Comment by FoxMcloud5655** [comment]
I don't even know how those two items function as I wasn't able to get them to work previously, but that's also because I didn't play with them extensively enough to figure them out.

I'll do what I can.

**Comment by FoxMcloud5655** [comment]
I was a big dumb and didn't override a certain method in each of the blocks that told MC that it has a tile entity attached to it.  Please feel free to test it thoroughly now.

**Comment by ercanserteli** [comment]
I just got around to testing this. It seems the blocks are working just fine now with that small fix. Thank you a lot!

**Pull request merged**
